### ISSUE TITLE
"RST" about half the time

### ISSUE THREAD

**Issue by olebowle** [madworm/Youyue-858D-plus#1]
Thanks for your alternative firmware.

Unfortunately I get "RST" roughly every second time I turn on the unit. Moreover, when I set the fan speed to maximum and start the unit I get "FANSPD". Is this expected without the current sens mod?

I'm using your binary and flashed it to a ATMEGA168-20PU with the following command:
`avrdude -patmega168 -cstk500v1 -P/dev/ttyUSB0 -b19200 -e -Uefuse:w:0x05:m -Uhfuse:w:0xdd:m -Ulfuse:w:0xe2:m -Uflash:w:2015-02-16__commit-9e3db57f__ATmega168-8MHz-RC-osc__FUSES-0xE2-0xDD-0xFD__V1.37-WDT.hex`

**Comment by madworm** [comment]
The FANSPD notice is expected behaviour. If you don't like it, you can change the low / high limits in the setup menu, or just set it to about 4 :-) Consult "modes_of_operation.txt" in the Docs folder.

Previously, there has been one case of an erroneous RST notice. This error message shows that the watchdog timer has fired and reset the unit. This should NEVER EVER happen. It indicates that something is wrong with the chip. The issue was resolved when the owner bought a genuine ATmega168 from a reputable source.

The FUSE values appear to be correct.

**Comment by olebowle** [comment]
Don't know if this one is genuine: http://www.ebay.de/itm/161141393953
I think I'll just go ahead and undefine USE_WATCHDOG.

Thanks for the quick response!
